version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: userservice_sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "15432:1433"  # Map host port 15432 to container port 1433
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
